### ISSUE TITLE
`autofill_service` does not specify a Swift version...

### ISSUE THREAD

**Issue by OGmetamonkey** [authpass/autofill_service#3]
The Android flutter app in the project builds great using autofill_service. The iOS project, however, fails on pod install with the following error. Any idea how to get the project to build without throwing this error?:

>     - `autofill_service` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:595:in `validate_targets'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:162:in `install!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
>     /usr/local/bin/pod:23:in `load'
>     /usr/local/bin/pod:23:in `<main>'
> Error output from CocoaPods:
> ↳
>     [!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> Exception: Error running pod install
> Exited (sigterm)

**Comment by OGmetamonkey** [comment]
This looks like a fairly common issue with plugins and was not related to this plugin. Closing now. See below for solution:

[https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482](solution)

> Bridging Header must be created.
> Open the project with XCode. Then choose File -> New -> File -> Swift File.
> A dialog will be displayed when creating the swift file(Since this file is deleted, any name can be used.). XCode will ask you if you wish to create Bridging Header, click yes.
> Make sure you have use_frameworks! in the Runner block, in ios/Podfile。
> Make sure you have SWIFT_VERSION 4.2 selected in you XCode -> Build Settings
> Do flutter clean
> Go to your ios folder, delete Podfile.lock and Pods folder and then execute pod install --repo-update
